### ISSUE TITLE
Support for CommentStream

### ISSUE THREAD

**Issue by WelliSolutions** [GregTheDev/MinidumpExplorer#18]
Hi. You mention:

> The following streams will not be added for now due to lack of available test data: CommentStreamA, 

Just a suggestion: you can open a crash dump in WinDbg and re-dump it with a comment, e.g.

```none
.dump /ma /c "This is a comment" dumpwithcomment.dmp
```

That way, you can generate arbitrary test data yourself, at least for CommentStreamW.

Also, [ProcDump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump) will generate crash dumps with comments be default, containing the command line used.

**Comment by WelliSolutions** [comment]
My bad. I just realized that you already have support for the W version.

**Comment by GregTheDev** [comment]
No worries, thanks for taking the time to reach out, appreciate it.
